#!/bin/bash
set -e

ln -sf /opt/2mhd-digital-twin/2mhd-digital-twin /usr/bin/2mhd-digital-twin
# Update icon cache if possible, but safe to ignore failures
gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true

exit 0
